/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoInsertFolderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  insertPosition: "top",
  format: "Folder: {{folder}}",
  allowedFolders: [],
  enableForAllFolders: true,
  insertMode: "body",
  frontmatterProperty: "folder",
  frontmatterFormat: "{{folder}}"
};
var AutoInsertFolderPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.processedFiles = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new AutoInsertFolderSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.handleNewFile(file);
        }
      })
    );
  }
  async handleNewFile(file) {
    try {
      if (this.processedFiles.has(file.path)) {
        return;
      }
      this.processedFiles.add(file.path);
      await this.sleep(200);
      if (!this.app.vault.getAbstractFileByPath(file.path)) {
        this.processedFiles.delete(file.path);
        return;
      }
      const parent = file.parent;
      if (!parent) {
        this.processedFiles.delete(file.path);
        return;
      }
      if (!this.isFolderAllowed(parent.path)) {
        this.processedFiles.delete(file.path);
        return;
      }
      const folderName = parent.path === "/" ? "Root" : parent.name;
      const content = await this.app.vault.read(file);
      if (content.trim().length > 0) {
        this.processedFiles.delete(file.path);
        return;
      }
      let newContent = "";
      if (this.settings.insertMode === "frontmatter" || this.settings.insertMode === "both") {
        newContent = this.insertFrontmatter(content, file);
      }
      if (this.settings.insertMode === "body" || this.settings.insertMode === "both") {
        const folderText = this.replacePlaceholders(this.settings.format, file);
        if (this.settings.insertMode === "both") {
          newContent = this.settings.insertPosition === "top" ? `${newContent}
${folderText}

` : `${newContent}

${folderText}`;
        } else {
          newContent = this.settings.insertPosition === "top" ? `${folderText}

` : `

${folderText}`;
        }
      }
      await this.app.vault.modify(file, newContent);
      this.processedFiles.delete(file.path);
    } catch (error) {
      console.error("Auto Insert Folder: Error handling new file", error);
      this.processedFiles.delete(file.path);
    }
  }
  replacePlaceholders(template, file) {
    const parent = file.parent;
    if (!parent)
      return template;
    const folderName = parent.path === "/" ? "Root" : parent.name;
    const grandparent = parent.parent;
    const grandparentName = grandparent ? grandparent.path === "/" ? "Root" : grandparent.name : "";
    return template.replace(/\{\{folder\}\}/g, folderName).replace(/\{\{parent\}\}/g, folderName).replace(/\{\{grandparent\}\}/g, grandparentName);
  }
  insertFrontmatter(content, file) {
    const formattedValue = this.replacePlaceholders(this.settings.frontmatterFormat, file);
    if (content.startsWith("---")) {
      const endOfFrontmatter = content.indexOf("---", 3);
      if (endOfFrontmatter > 0) {
        const frontmatterContent = content.substring(4, endOfFrontmatter).trim();
        const restOfContent = content.substring(endOfFrontmatter + 3);
        return `---
${frontmatterContent}
${this.settings.frontmatterProperty}: ${formattedValue}
---${restOfContent}`;
      }
    }
    return `---
${this.settings.frontmatterProperty}: ${formattedValue}
---
`;
  }
  isFolderAllowed(folderPath) {
    if (this.settings.enableForAllFolders) {
      return true;
    }
    const normalizedPath = folderPath.replace(/\\/g, "/");
    return this.settings.allowedFolders.some((allowedFolder) => {
      const normalizedAllowed = allowedFolder.replace(/\\/g, "/");
      return normalizedPath === normalizedAllowed || normalizedPath.startsWith(normalizedAllowed + "/");
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
};
var AutoInsertFolderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Auto Insert Folder Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable for all folders").setDesc("If enabled, the plugin will work in all folders. If disabled, only specific folders will be processed.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableForAllFolders).onChange(async (value) => {
      this.plugin.settings.enableForAllFolders = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (!this.plugin.settings.enableForAllFolders) {
      new import_obsidian.Setting(containerEl).setName("Allowed folders").setDesc("Enter folder paths (one per line) where auto-insert should be enabled. Subfolders are automatically included.").addTextArea((text) => text.setPlaceholder("Projects\nWork/Notes\nPersonal").setValue(this.plugin.settings.allowedFolders.join("\n")).onChange(async (value) => {
        this.plugin.settings.allowedFolders = value.split("\n").map((f) => f.trim()).filter((f) => f.length > 0);
        await this.plugin.saveSettings();
      }).then((textArea) => {
        textArea.inputEl.rows = 8;
        textArea.inputEl.cols = 30;
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Insert mode").setDesc("Choose where to insert the folder name: in the note body, frontmatter, or both.").addDropdown((dropdown) => dropdown.addOption("body", "Body text only").addOption("frontmatter", "Frontmatter only").addOption("both", "Both body and frontmatter").setValue(this.plugin.settings.insertMode).onChange(async (value) => {
      this.plugin.settings.insertMode = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.insertMode === "frontmatter" || this.plugin.settings.insertMode === "both") {
      new import_obsidian.Setting(containerEl).setName("Frontmatter property").setDesc('The property name to use in frontmatter (e.g., "folder", "location", "category").').addText((text) => text.setPlaceholder("folder").setValue(this.plugin.settings.frontmatterProperty).onChange(async (value) => {
        this.plugin.settings.frontmatterProperty = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Frontmatter value format").setDesc('Format for the frontmatter value. Available placeholders: {{folder}}/{{parent}} (folder name), {{grandparent}} (parent folder). Examples: "[[{{folder}}]]", "{{grandparent}}/{{folder}}"').addText((text) => text.setPlaceholder("{{folder}}").setValue(this.plugin.settings.frontmatterFormat).onChange(async (value) => {
        this.plugin.settings.frontmatterFormat = value;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.insertMode === "body" || this.plugin.settings.insertMode === "both") {
      new import_obsidian.Setting(containerEl).setName("Insert format").setDesc("Text to insert in body. Available placeholders: {{folder}}/{{parent}} (folder name), {{grandparent}} (parent folder).").addText((text) => text.setPlaceholder("Folder: {{folder}}").setValue(this.plugin.settings.format).onChange(async (value) => {
        this.plugin.settings.format = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Insert position").setDesc("Where to insert the folder text in the note body").addDropdown((dropdown) => dropdown.addOption("top", "Top of note").addOption("bottom", "Bottom of note").setValue(this.plugin.settings.insertPosition).onChange(async (value) => {
        this.plugin.settings.insertPosition = value;
        await this.plugin.saveSettings();
      }));
    }
  }
};
